# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tesla_api/protobuf/energy_device/v1/authorization_record.proto
# Protobuf Python Version: 6.33.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    0,
    '',
    'tesla_api/protobuf/energy_device/v1/authorization_record.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from tesla_api.protobuf.energy_device.v1 import authorization_role_pb2 as tesla__api_dot_protobuf_dot_energy__device_dot_v1_dot_authorization__role__pb2
from tesla_api.protobuf.energy_device.v1 import authorized_client_type_pb2 as tesla__api_dot_protobuf_dot_energy__device_dot_v1_dot_authorized__client__type__pb2
from tesla_api.protobuf.energy_device.v1 import authorized_key_type_pb2 as tesla__api_dot_protobuf_dot_energy__device_dot_v1_dot_authorized__key__type__pb2
from tesla_api.protobuf.energy_device.v1 import authorized_state_pb2 as tesla__api_dot_protobuf_dot_energy__device_dot_v1_dot_authorized__state__pb2
from tesla_api.protobuf.energy_device.v1 import authorized_verification_type_pb2 as tesla__api_dot_protobuf_dot_energy__device_dot_v1_dot_authorized__verification__type__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n>tesla_api/protobuf/energy_device/v1/authorization_record.proto\x12\x1ctesla.proto.energy_device.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a<tesla_api/protobuf/energy_device/v1/authorization_role.proto\x1a@tesla_api/protobuf/energy_device/v1/authorized_client_type.proto\x1a=tesla_api/protobuf/energy_device/v1/authorized_key_type.proto\x1a:tesla_api/protobuf/energy_device/v1/authorized_state.proto\x1a\x46tesla_api/protobuf/energy_device/v1/authorized_verification_type.proto\"\xf7\x03\n\x13\x41uthorizationRecord\x12@\n\x04type\x18\x01 \x01(\x0e\x32\x32.tesla.proto.energy_device.v1.AuthorizedClientType\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x41\n\x08key_type\x18\x03 \x01(\x0e\x32/.tesla.proto.energy_device.v1.AuthorizedKeyType\x12\x12\n\npublic_key\x18\x04 \x01(\x0c\x12>\n\x05roles\x18\x05 \x03(\x0e\x32/.tesla.proto.energy_device.v1.AuthorizationRole\x12<\n\x05state\x18\x06 \x01(\x0e\x32-.tesla.proto.energy_device.v1.AuthorizedState\x12N\n\x0cverification\x18\x07 \x01(\x0e\x32\x38.tesla.proto.energy_device.v1.AuthorizedVerificationType\x12.\n\nadded_time\x18\x08 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x12\n\nidentifier\x18\t \x01(\t\x12 \n\x18\x61uthorized_by_public_key\x18\n \x01(\x0c\x42\x87\x01\n$com.tesla.generated.energy_device.v1B\x13\x41uthorizationRecordZJgithub.com/teslamotors/energy_device/pkg/protocol/protobuf/energydevice/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tesla_api.protobuf.energy_device.v1.authorization_record_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n$com.tesla.generated.energy_device.v1B\023AuthorizationRecordZJgithub.com/teslamotors/energy_device/pkg/protocol/protobuf/energydevice/v1'
  _globals['_AUTHORIZATIONRECORD']._serialized_start=453
  _globals['_AUTHORIZATIONRECORD']._serialized_end=956
# @@protoc_insertion_point(module_scope)
