# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tesla_api/protobuf/energy_device/v1/authorization_role.proto
# Protobuf Python Version: 6.33.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    0,
    '',
    'tesla_api/protobuf/energy_device/v1/authorization_role.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n<tesla_api/protobuf/energy_device/v1/authorization_role.proto\x12\x1ctesla.proto.energy_device.v1*t\n\x11\x41uthorizationRole\x12\x1e\n\x1a\x41UTHORIZATION_ROLE_INVALID\x10\x00\x12\x1f\n\x1b\x41UTHORIZATION_ROLE_CUSTOMER\x10\x01\x12\x1e\n\x1a\x41UTHORIZATION_ROLE_VEHICLE\x10\x02\x42\x85\x01\n$com.tesla.generated.energy_device.v1B\x11\x41uthorizationRoleZJgithub.com/teslamotors/energy_device/pkg/protocol/protobuf/energydevice/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tesla_api.protobuf.energy_device.v1.authorization_role_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n$com.tesla.generated.energy_device.v1B\021AuthorizationRoleZJgithub.com/teslamotors/energy_device/pkg/protocol/protobuf/energydevice/v1'
  _globals['_AUTHORIZATIONROLE']._serialized_start=94
  _globals['_AUTHORIZATIONROLE']._serialized_end=210
# @@protoc_insertion_point(module_scope)
