# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tesla_api/protobuf/energy_device/v1/authorized_state.proto
# Protobuf Python Version: 6.33.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    0,
    '',
    'tesla_api/protobuf/energy_device/v1/authorized_state.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n:tesla_api/protobuf/energy_device/v1/authorized_state.proto\x12\x1ctesla.proto.energy_device.v1*\xca\x01\n\x0f\x41uthorizedState\x12\x1c\n\x18\x41UTHORIZED_STATE_INVALID\x10\x00\x12)\n%AUTHORIZED_STATE_PENDING_VERIFICATION\x10\x01\x12\x31\n-AUTHORIZED_STATE_PENDING_VERIFICATION_TIMEOUT\x10\x02\x12\x1d\n\x19\x41UTHORIZED_STATE_VERIFIED\x10\x03\x12\x1c\n\x18\x41UTHORIZED_STATE_REMOVED\x10\x04\x42\x83\x01\n$com.tesla.generated.energy_device.v1B\x0f\x41uthorizedStateZJgithub.com/teslamotors/energy_device/pkg/protocol/protobuf/energydevice/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tesla_api.protobuf.energy_device.v1.authorized_state_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n$com.tesla.generated.energy_device.v1B\017AuthorizedStateZJgithub.com/teslamotors/energy_device/pkg/protocol/protobuf/energydevice/v1'
  _globals['_AUTHORIZEDSTATE']._serialized_start=93
  _globals['_AUTHORIZEDSTATE']._serialized_end=295
# @@protoc_insertion_point(module_scope)
