# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tesla_api/protobuf/energy_device/v1/auth_envelope.proto
# Protobuf Python Version: 6.33.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    0,
    '',
    'tesla_api/protobuf/energy_device/v1/auth_envelope.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tesla_api.protobuf.energy_device.v1 import external_auth_pb2 as tesla__api_dot_protobuf_dot_energy__device_dot_v1_dot_external__auth__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n7tesla_api/protobuf/energy_device/v1/auth_envelope.proto\x12\x1ctesla.proto.energy_device.v1\x1a\x37tesla_api/protobuf/energy_device/v1/external_auth.proto\"l\n\x0c\x41uthEnvelope\x12\x0f\n\x07payload\x18\x01 \x01(\x0c\x12\x43\n\rexternal_auth\x18\x02 \x01(\x0b\x32*.tesla.proto.energy_device.v1.ExternalAuthH\x00\x42\x06\n\x04\x61uthB\x80\x01\n$com.tesla.generated.energy_device.v1B\x0c\x41uthEnvelopeZJgithub.com/teslamotors/energy_device/pkg/protocol/protobuf/energydevice/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tesla_api.protobuf.energy_device.v1.auth_envelope_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n$com.tesla.generated.energy_device.v1B\014AuthEnvelopeZJgithub.com/teslamotors/energy_device/pkg/protocol/protobuf/energydevice/v1'
  _globals['_AUTHENVELOPE']._serialized_start=146
  _globals['_AUTHENVELOPE']._serialized_end=254
# @@protoc_insertion_point(module_scope)
