# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tesla_api/protobuf/energy_device/v1/cellular_profile_type.proto
# Protobuf Python Version: 6.33.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    0,
    '',
    'tesla_api/protobuf/energy_device/v1/cellular_profile_type.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n?tesla_api/protobuf/energy_device/v1/cellular_profile_type.proto\x12\x1ctesla.proto.energy_device.v1*\xc6\x02\n\x13\x43\x65llularProfileType\x12!\n\x1d\x43\x45LLULAR_PROFILE_TYPE_INVALID\x10\x00\x12 \n\x1c\x43\x45LLULAR_PROFILE_TYPE_TWILIO\x10\x01\x12\x1d\n\x19\x43\x45LLULAR_PROFILE_TYPE_ATT\x10\x02\x12\x1d\n\x19\x43\x45LLULAR_PROFILE_TYPE_KPN\x10\x03\x12$\n CELLULAR_PROFILE_TYPE_TELEFONICA\x10\x04\x12!\n\x1d\x43\x45LLULAR_PROFILE_TYPE_TELSTRA\x10\x05\x12\x1f\n\x1b\x43\x45LLULAR_PROFILE_TYPE_TELUS\x10\x06\x12 \n\x1c\x43\x45LLULAR_PROFILE_TYPE_DOCOMO\x10\x07\x12 \n\x1c\x43\x45LLULAR_PROFILE_TYPE_UNICOM\x10\x08\x42\x87\x01\n$com.tesla.generated.energy_device.v1B\x13\x43\x65llularProfileTypeZJgithub.com/teslamotors/energy_device/pkg/protocol/protobuf/energydevice/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tesla_api.protobuf.energy_device.v1.cellular_profile_type_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n$com.tesla.generated.energy_device.v1B\023CellularProfileTypeZJgithub.com/teslamotors/energy_device/pkg/protocol/protobuf/energydevice/v1'
  _globals['_CELLULARPROFILETYPE']._serialized_start=98
  _globals['_CELLULARPROFILETYPE']._serialized_end=424
# @@protoc_insertion_point(module_scope)
