# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tesla_api/protobuf/energy_device/v1/common_api_wifi_scan_request.proto
# Protobuf Python Version: 6.33.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    0,
    '',
    'tesla_api/protobuf/energy_device/v1/common_api_wifi_scan_request.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tesla_api.protobuf.energy_device.v1 import wifi_network_security_type_pb2 as tesla__api_dot_protobuf_dot_energy__device_dot_v1_dot_wifi__network__security__type__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nFtesla_api/protobuf/energy_device/v1/common_api_wifi_scan_request.proto\x12\x1ctesla.proto.energy_device.v1\x1a\x44tesla_api/protobuf/energy_device/v1/wifi_network_security_type.proto\"\xa9\x01\n\x18\x43ommonAPIWifiScanRequest\x12\x1b\n\x13max_scan_duration_s\x18\x01 \x01(\r\x12U\n\x16\x64\x65sired_security_types\x18\x02 \x03(\x0e\x32\x35.tesla.proto.energy_device.v1.WifiNetworkSecurityType\x12\x19\n\x11maximum_total_aps\x18\x03 \x01(\rB\x8c\x01\n$com.tesla.generated.energy_device.v1B\x18\x43ommonAPIWifiScanRequestZJgithub.com/teslamotors/energy_device/pkg/protocol/protobuf/energydevice/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tesla_api.protobuf.energy_device.v1.common_api_wifi_scan_request_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n$com.tesla.generated.energy_device.v1B\030CommonAPIWifiScanRequestZJgithub.com/teslamotors/energy_device/pkg/protocol/protobuf/energydevice/v1'
  _globals['_COMMONAPIWIFISCANREQUEST']._serialized_start=175
  _globals['_COMMONAPIWIFISCANREQUEST']._serialized_end=344
# @@protoc_insertion_point(module_scope)
