# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tesla_api/protobuf/energy_device/v1/common_api_prepare_registration_payload_request.proto
# Protobuf Python Version: 6.33.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    0,
    '',
    'tesla_api/protobuf/energy_device/v1/common_api_prepare_registration_payload_request.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nYtesla_api/protobuf/energy_device/v1/common_api_prepare_registration_payload_request.proto\x12\x1ctesla.proto.energy_device.v1\"P\n*CommonAPIPrepareRegistrationPayloadRequest\x12\"\n\x1a\x63ustomer_registration_info\x18\x01 \x01(\x0c\x42\x9e\x01\n$com.tesla.generated.energy_device.v1B*CommonAPIPrepareRegistrationPayloadRequestZJgithub.com/teslamotors/energy_device/pkg/protocol/protobuf/energydevice/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tesla_api.protobuf.energy_device.v1.common_api_prepare_registration_payload_request_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n$com.tesla.generated.energy_device.v1B*CommonAPIPrepareRegistrationPayloadRequestZJgithub.com/teslamotors/energy_device/pkg/protocol/protobuf/energydevice/v1'
  _globals['_COMMONAPIPREPAREREGISTRATIONPAYLOADREQUEST']._serialized_start=123
  _globals['_COMMONAPIPREPAREREGISTRATIONPAYLOADREQUEST']._serialized_end=203
# @@protoc_insertion_point(module_scope)
