# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tesla_api/protobuf/energy_device/v1/common_api_perform_update_from_locally_available_packages_request.proto
# Protobuf Python Version: 6.33.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    0,
    '',
    'tesla_api/protobuf/energy_device/v1/common_api_perform_update_from_locally_available_packages_request.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tesla_api.protobuf.energy_device.v1 import locally_available_package_pb2 as tesla__api_dot_protobuf_dot_energy__device_dot_v1_dot_locally__available__package__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nktesla_api/protobuf/energy_device/v1/common_api_perform_update_from_locally_available_packages_request.proto\x12\x1ctesla.proto.energy_device.v1\x1a\x43tesla_api/protobuf/energy_device/v1/locally_available_package.proto\"\x96\x01\n9CommonAPIPerformUpdateFromLocallyAvailablePackagesRequest\x12Y\n\x1alocally_available_packages\x18\x01 \x03(\x0b\x32\x35.tesla.proto.energy_device.v1.LocallyAvailablePackageB\xad\x01\n$com.tesla.generated.energy_device.v1B9CommonAPIPerformUpdateFromLocallyAvailablePackagesRequestZJgithub.com/teslamotors/energy_device/pkg/protocol/protobuf/energydevice/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tesla_api.protobuf.energy_device.v1.common_api_perform_update_from_locally_available_packages_request_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n$com.tesla.generated.energy_device.v1B9CommonAPIPerformUpdateFromLocallyAvailablePackagesRequestZJgithub.com/teslamotors/energy_device/pkg/protocol/protobuf/energydevice/v1'
  _globals['_COMMONAPIPERFORMUPDATEFROMLOCALLYAVAILABLEPACKAGESREQUEST']._serialized_start=211
  _globals['_COMMONAPIPERFORMUPDATEFROMLOCALLYAVAILABLEPACKAGESREQUEST']._serialized_end=361
# @@protoc_insertion_point(module_scope)
