# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tesla_api/protobuf/energy_device/v1/common_api_check_internet_response.proto
# Protobuf Python Version: 6.33.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    0,
    '',
    'tesla_api/protobuf/energy_device/v1/common_api_check_internet_response.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tesla_api.protobuf.energy_device.v1 import network_interface_pb2 as tesla__api_dot_protobuf_dot_energy__device_dot_v1_dot_network__interface__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nLtesla_api/protobuf/energy_device/v1/common_api_check_internet_response.proto\x12\x1ctesla.proto.energy_device.v1\x1a;tesla_api/protobuf/energy_device/v1/network_interface.proto\"\xd8\x01\n\x1e\x43ommonAPICheckInternetResponse\x12<\n\x04wifi\x18\x01 \x01(\x0b\x32..tesla.proto.energy_device.v1.NetworkInterface\x12;\n\x03\x65th\x18\x02 \x01(\x0b\x32..tesla.proto.energy_device.v1.NetworkInterface\x12;\n\x03gsm\x18\x03 \x01(\x0b\x32..tesla.proto.energy_device.v1.NetworkInterfaceB\x92\x01\n$com.tesla.generated.energy_device.v1B\x1e\x43ommonAPICheckInternetResponseZJgithub.com/teslamotors/energy_device/pkg/protocol/protobuf/energydevice/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tesla_api.protobuf.energy_device.v1.common_api_check_internet_response_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n$com.tesla.generated.energy_device.v1B\036CommonAPICheckInternetResponseZJgithub.com/teslamotors/energy_device/pkg/protocol/protobuf/energydevice/v1'
  _globals['_COMMONAPICHECKINTERNETRESPONSE']._serialized_start=172
  _globals['_COMMONAPICHECKINTERNETRESPONSE']._serialized_end=388
# @@protoc_insertion_point(module_scope)
