# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tesla_api/protobuf/energy_device/v1/common_api_configure_wifi_with_encrypted_password_request.proto
# Protobuf Python Version: 6.33.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    0,
    '',
    'tesla_api/protobuf/energy_device/v1/common_api_configure_wifi_with_encrypted_password_request.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tesla_api.protobuf.energy_device.v1 import encrypted_message_pb2 as tesla__api_dot_protobuf_dot_energy__device_dot_v1_dot_encrypted__message__pb2
from tesla_api.protobuf.energy_device.v1 import wifi_config_pb2 as tesla__api_dot_protobuf_dot_energy__device_dot_v1_dot_wifi__config__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nctesla_api/protobuf/energy_device/v1/common_api_configure_wifi_with_encrypted_password_request.proto\x12\x1ctesla.proto.energy_device.v1\x1a;tesla_api/protobuf/energy_device/v1/encrypted_message.proto\x1a\x35tesla_api/protobuf/energy_device/v1/wifi_config.proto\"\xd0\x01\n2CommonAPIConfigureWifiWithEncryptedPasswordRequest\x12\x0f\n\x07\x65nabled\x18\x01 \x01(\x08\x12=\n\x0bwifi_config\x18\x02 \x01(\x0b\x32(.tesla.proto.energy_device.v1.WifiConfig\x12J\n\x12\x65ncrypted_password\x18\x03 \x01(\x0b\x32..tesla.proto.energy_device.v1.EncryptedMessageB\xa6\x01\n$com.tesla.generated.energy_device.v1B2CommonAPIConfigureWifiWithEncryptedPasswordRequestZJgithub.com/teslamotors/energy_device/pkg/protocol/protobuf/energydevice/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tesla_api.protobuf.energy_device.v1.common_api_configure_wifi_with_encrypted_password_request_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n$com.tesla.generated.energy_device.v1B2CommonAPIConfigureWifiWithEncryptedPasswordRequestZJgithub.com/teslamotors/energy_device/pkg/protocol/protobuf/energydevice/v1'
  _globals['_COMMONAPICONFIGUREWIFIWITHENCRYPTEDPASSWORDREQUEST']._serialized_start=250
  _globals['_COMMONAPICONFIGUREWIFIWITHENCRYPTEDPASSWORDREQUEST']._serialized_end=458
# @@protoc_insertion_point(module_scope)
