# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tesla_api/protobuf/energy_device/v1/common_api_get_cellular_info_response.proto
# Protobuf Python Version: 6.33.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    0,
    '',
    'tesla_api/protobuf/energy_device/v1/common_api_get_cellular_info_response.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tesla_api.protobuf.energy_device.v1 import cellular_eid_pb2 as tesla__api_dot_protobuf_dot_energy__device_dot_v1_dot_cellular__eid__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nOtesla_api/protobuf/energy_device/v1/common_api_get_cellular_info_response.proto\x12\x1ctesla.proto.energy_device.v1\x1a\x36tesla_api/protobuf/energy_device/v1/cellular_eid.proto\"v\n CommonAPIGetCellularInfoResponse\x12\x36\n\x03\x65id\x18\x01 \x01(\x0b\x32).tesla.proto.energy_device.v1.CellularEID\x12\x1a\n\x12supported_profiles\x18\x02 \x03(\x05\x42\x94\x01\n$com.tesla.generated.energy_device.v1B CommonAPIGetCellularInfoResponseZJgithub.com/teslamotors/energy_device/pkg/protocol/protobuf/energydevice/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tesla_api.protobuf.energy_device.v1.common_api_get_cellular_info_response_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n$com.tesla.generated.energy_device.v1B CommonAPIGetCellularInfoResponseZJgithub.com/teslamotors/energy_device/pkg/protocol/protobuf/energydevice/v1'
  _globals['_COMMONAPIGETCELLULARINFORESPONSE']._serialized_start=169
  _globals['_COMMONAPIGETCELLULARINFORESPONSE']._serialized_end=287
# @@protoc_insertion_point(module_scope)
