# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tesla_api/protobuf/energy_device/v1/common_api_get_system_info_response.proto
# Protobuf Python Version: 6.33.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    0,
    '',
    'tesla_api/protobuf/energy_device/v1/common_api_get_system_info_response.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tesla_api.protobuf.energy_device.v1 import device_type_pb2 as tesla__api_dot_protobuf_dot_energy__device_dot_v1_dot_device__type__pb2
from tesla_api.protobuf.energy_device.v1 import din_pb2 as tesla__api_dot_protobuf_dot_energy__device_dot_v1_dot_din__pb2
from tesla_api.protobuf.energy_device.v1 import ecu_id_pb2 as tesla__api_dot_protobuf_dot_energy__device_dot_v1_dot_ecu__id__pb2
from tesla_api.protobuf.energy_device.v1 import firmware_version_pb2 as tesla__api_dot_protobuf_dot_energy__device_dot_v1_dot_firmware__version__pb2
from tesla_api.protobuf.energy_device.v1 import system_update_pb2 as tesla__api_dot_protobuf_dot_energy__device_dot_v1_dot_system__update__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nMtesla_api/protobuf/energy_device/v1/common_api_get_system_info_response.proto\x12\x1ctesla.proto.energy_device.v1\x1a\x35tesla_api/protobuf/energy_device/v1/device_type.proto\x1a-tesla_api/protobuf/energy_device/v1/din.proto\x1a\x30tesla_api/protobuf/energy_device/v1/ecu_id.proto\x1a:tesla_api/protobuf/energy_device/v1/firmware_version.proto\x1a\x37tesla_api/protobuf/energy_device/v1/system_update.proto\"\xd2\x02\n\x1e\x43ommonAPIGetSystemInfoResponse\x12\x36\n\tdevice_id\x18\x01 \x01(\x0b\x32#.tesla.proto.energy_device.v1.EcuId\x12.\n\x03\x64in\x18\x02 \x01(\x0b\x32!.tesla.proto.energy_device.v1.Din\x12\x46\n\x0f\x66irmare_version\x18\x03 \x01(\x0b\x32-.tesla.proto.energy_device.v1.FirmwareVersion\x12\x41\n\rsystem_update\x18\x04 \x01(\x0b\x32*.tesla.proto.energy_device.v1.SystemUpdate\x12=\n\x0b\x64\x65vice_type\x18\x05 \x01(\x0e\x32(.tesla.proto.energy_device.v1.DeviceTypeB\x92\x01\n$com.tesla.generated.energy_device.v1B\x1e\x43ommonAPIGetSystemInfoResponseZJgithub.com/teslamotors/energy_device/pkg/protocol/protobuf/energydevice/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tesla_api.protobuf.energy_device.v1.common_api_get_system_info_response_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n$com.tesla.generated.energy_device.v1B\036CommonAPIGetSystemInfoResponseZJgithub.com/teslamotors/energy_device/pkg/protocol/protobuf/energydevice/v1'
  _globals['_COMMONAPIGETSYSTEMINFORESPONSE']._serialized_start=381
  _globals['_COMMONAPIGETSYSTEMINFORESPONSE']._serialized_end=719
# @@protoc_insertion_point(module_scope)
