# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tesla_api/protobuf/energy_device/v1/device_signature_type.proto
# Protobuf Python Version: 6.33.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    0,
    '',
    'tesla_api/protobuf/energy_device/v1/device_signature_type.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n?tesla_api/protobuf/energy_device/v1/device_signature_type.proto\x12\x1ctesla.proto.energy_device.v1*e\n\x13\x44\x65viceSignatureType\x12!\n\x1d\x44\x45VICE_SIGNATURE_TYPE_INVALID\x10\x00\x12+\n\'DEVICE_SIGNATURE_TYPE_SHA256_ECDSA_ASN1\x10\x01\x42\x87\x01\n$com.tesla.generated.energy_device.v1B\x13\x44\x65viceSignatureTypeZJgithub.com/teslamotors/energy_device/pkg/protocol/protobuf/energydevice/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tesla_api.protobuf.energy_device.v1.device_signature_type_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n$com.tesla.generated.energy_device.v1B\023DeviceSignatureTypeZJgithub.com/teslamotors/energy_device/pkg/protocol/protobuf/energydevice/v1'
  _globals['_DEVICESIGNATURETYPE']._serialized_start=97
  _globals['_DEVICESIGNATURETYPE']._serialized_end=198
# @@protoc_insertion_point(module_scope)
