# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tesla_api/protobuf/energy_device/v1/device_type.proto
# Protobuf Python Version: 6.33.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    0,
    '',
    'tesla_api/protobuf/energy_device/v1/device_type.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n5tesla_api/protobuf/energy_device/v1/device_type.proto\x12\x1ctesla.proto.energy_device.v1*\xb9\x01\n\nDeviceType\x12\x17\n\x13\x44\x45VICE_TYPE_INVALID\x10\x00\x12\x16\n\x12\x44\x45VICE_TYPE_GEN3WC\x10\x01\x12\x15\n\x11\x44\x45VICE_TYPE_PVCOM\x10\x02\x12\x13\n\x0f\x44\x45VICE_TYPE_MSA\x10\x03\x12\x1e\n\x1a\x44\x45VICE_TYPE_SITECONTROLLER\x10\x04\x12\x19\n\x15\x44\x45VICE_TYPE_MEGAPUTER\x10\x05\x12\x13\n\x0f\x44\x45VICE_TYPE_IPM\x10\x06\x42~\n$com.tesla.generated.energy_device.v1B\nDeviceTypeZJgithub.com/teslamotors/energy_device/pkg/protocol/protobuf/energydevice/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tesla_api.protobuf.energy_device.v1.device_type_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n$com.tesla.generated.energy_device.v1B\nDeviceTypeZJgithub.com/teslamotors/energy_device/pkg/protocol/protobuf/energydevice/v1'
  _globals['_DEVICETYPE']._serialized_start=88
  _globals['_DEVICETYPE']._serialized_end=273
# @@protoc_insertion_point(module_scope)
