# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tesla_api/protobuf/energy_device/v1/device_signed_payload.proto
# Protobuf Python Version: 6.33.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    0,
    '',
    'tesla_api/protobuf/energy_device/v1/device_signed_payload.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tesla_api.protobuf.energy_device.v1 import device_cert_format_pb2 as tesla__api_dot_protobuf_dot_energy__device_dot_v1_dot_device__cert__format__pb2
from tesla_api.protobuf.energy_device.v1 import device_signature_type_pb2 as tesla__api_dot_protobuf_dot_energy__device_dot_v1_dot_device__signature__type__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n?tesla_api/protobuf/energy_device/v1/device_signed_payload.proto\x12\x1ctesla.proto.energy_device.v1\x1a<tesla_api/protobuf/energy_device/v1/device_cert_format.proto\x1a?tesla_api/protobuf/energy_device/v1/device_signature_type.proto\"\xec\x01\n\x13\x44\x65viceSignedPayload\x12\x0f\n\x07payload\x18\x01 \x01(\x0c\x12P\n\x15\x64\x65vice_signature_type\x18\x02 \x01(\x0e\x32\x31.tesla.proto.energy_device.v1.DeviceSignatureType\x12\x11\n\tsignature\x18\x03 \x01(\x0c\x12J\n\x12\x64\x65vice_cert_format\x18\x04 \x01(\x0e\x32..tesla.proto.energy_device.v1.DeviceCertFormat\x12\x13\n\x0b\x64\x65vice_cert\x18\x05 \x01(\x0c\x42\x87\x01\n$com.tesla.generated.energy_device.v1B\x13\x44\x65viceSignedPayloadZJgithub.com/teslamotors/energy_device/pkg/protocol/protobuf/energydevice/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tesla_api.protobuf.energy_device.v1.device_signed_payload_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n$com.tesla.generated.energy_device.v1B\023DeviceSignedPayloadZJgithub.com/teslamotors/energy_device/pkg/protocol/protobuf/energydevice/v1'
  _globals['_DEVICESIGNEDPAYLOAD']._serialized_start=225
  _globals['_DEVICESIGNEDPAYLOAD']._serialized_end=461
# @@protoc_insertion_point(module_scope)
