# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tesla_api/protobuf/energy_device/v1/encrypted_message.proto
# Protobuf Python Version: 6.33.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    0,
    '',
    'tesla_api/protobuf/energy_device/v1/encrypted_message.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tesla_api.protobuf.energy_device.v1 import cipher_pb2 as tesla__api_dot_protobuf_dot_energy__device_dot_v1_dot_cipher__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n;tesla_api/protobuf/energy_device/v1/encrypted_message.proto\x12\x1ctesla.proto.energy_device.v1\x1a\x30tesla_api/protobuf/energy_device/v1/cipher.proto\"]\n\x10\x45ncryptedMessage\x12\x34\n\x06\x63ipher\x18\x01 \x01(\x0e\x32$.tesla.proto.energy_device.v1.Cipher\x12\x13\n\x0b\x63ipher_text\x18\x02 \x01(\x0c\x42\x84\x01\n$com.tesla.generated.energy_device.v1B\x10\x45ncryptedMessageZJgithub.com/teslamotors/energy_device/pkg/protocol/protobuf/energydevice/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tesla_api.protobuf.energy_device.v1.encrypted_message_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n$com.tesla.generated.energy_device.v1B\020EncryptedMessageZJgithub.com/teslamotors/energy_device/pkg/protocol/protobuf/energydevice/v1'
  _globals['_ENCRYPTEDMESSAGE']._serialized_start=143
  _globals['_ENCRYPTEDMESSAGE']._serialized_end=236
# @@protoc_insertion_point(module_scope)
