# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tesla_api/protobuf/energy_device/v1/energy_site_net_network_type.proto
# Protobuf Python Version: 6.33.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    0,
    '',
    'tesla_api/protobuf/energy_device/v1/energy_site_net_network_type.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nFtesla_api/protobuf/energy_device/v1/energy_site_net_network_type.proto*\xd1\x01\n\x18\x45nergySiteNetNetworkType\x12(\n$ENERGY_SITE_NET_NETWORK_TYPE_INVALID\x10\x00\x12+\n\'ENERGY_SITE_NET_NETWORK_TYPE_POWERWALL3\x10\x01\x12/\n+ENERGY_SITE_NET_NETWORK_TYPE_SMART_CHARGING\x10\x02\x12-\n)ENERGY_SITE_NET_NETWORK_TYPE_LOAD_SHARING\x10\x03')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tesla_api.protobuf.energy_device.v1.energy_site_net_network_type_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ENERGYSITENETNETWORKTYPE']._serialized_start=75
  _globals['_ENERGYSITENETNETWORKTYPE']._serialized_end=284
# @@protoc_insertion_point(module_scope)
