# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tesla_api/protobuf/energy_device/v1/energy_site_net_addition_status.proto
# Protobuf Python Version: 6.33.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    0,
    '',
    'tesla_api/protobuf/energy_device/v1/energy_site_net_addition_status.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nItesla_api/protobuf/energy_device/v1/energy_site_net_addition_status.proto*\xdf\x05\n\x1b\x45nergySiteNetAdditionStatus\x12+\n\'ENERGY_SITE_NET_ADDITION_STATUS_INVALID\x10\x00\x12/\n+ENERGY_SITE_NET_ADDITION_STATUS_IN_PROGRESS\x10\x01\x12)\n%ENERGY_SITE_NET_ADDITION_STATUS_ADDED\x10\x02\x12\x34\n0ENERGY_SITE_NET_ADDITION_STATUS_FAILED_NOT_FOUND\x10\x03\x12\x36\n2ENERGY_SITE_NET_ADDITION_STATUS_FAILED_CANNOT_JOIN\x10\x04\x12\x36\n2ENERGY_SITE_NET_ADDITION_STATUS_FAILED_NO_RESPONSE\x10\x05\x12\x37\n3ENERGY_SITE_NET_ADDITION_STATUS_FAILED_BAD_RESPONSE\x10\x06\x12\x39\n5ENERGY_SITE_NET_ADDITION_STATUS_FAILED_INTERNAL_ERROR\x10\x07\x12=\n9ENERGY_SITE_NET_ADDITION_STATUS_FAILED_CHANGES_PROHIBITED\x10\x08\x12\x36\n2ENERGY_SITE_NET_ADDITION_STATUS_FAILED_MAX_DEVICES\x10\t\x12\x35\n1ENERGY_SITE_NET_ADDITION_STATUS_FAILED_NOT_LEADER\x10\n\x12\x31\n-ENERGY_SITE_NET_ADDITION_STATUS_FAILED_EXISTS\x10\x0b\x12<\n8ENERGY_SITE_NET_ADDITION_STATUS_FAILED_PROOF_OF_PRESENCE\x10\x0c')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tesla_api.protobuf.energy_device.v1.energy_site_net_addition_status_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ENERGYSITENETADDITIONSTATUS']._serialized_start=78
  _globals['_ENERGYSITENETADDITIONSTATUS']._serialized_end=813
# @@protoc_insertion_point(module_scope)
