# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tesla_api/protobuf/energy_device/v1/energy_site_net_pair_status.proto
# Protobuf Python Version: 6.33.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    0,
    '',
    'tesla_api/protobuf/energy_device/v1/energy_site_net_pair_status.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nEtesla_api/protobuf/energy_device/v1/energy_site_net_pair_status.proto\x12\x1ctesla.proto.energy_device.v1*\xd9\x01\n\x13\x45nergyNetPairStatus\x12\'\n#ENERGY_SITE_NET_PAIR_STATUS_INVALID\x10\x00\x12\'\n#ENERGY_SITE_NET_PAIR_STATUS_PENDING\x10\x01\x12\x35\n1ENERGY_SITE_NET_PAIR_STATUS_FAILED_INTERNAL_ERROR\x10\x02\x12\x39\n5ENERGY_SITE_NET_PAIR_STATUS_PROOF_OF_PRESENCE_TIMEOUT\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tesla_api.protobuf.energy_device.v1.energy_site_net_pair_status_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ENERGYNETPAIRSTATUS']._serialized_start=104
  _globals['_ENERGYNETPAIRSTATUS']._serialized_end=321
# @@protoc_insertion_point(module_scope)
