# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tesla_api/protobuf/energy_device/v1/energy_accumulation_type.proto
# Protobuf Python Version: 6.33.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    0,
    '',
    'tesla_api/protobuf/energy_device/v1/energy_accumulation_type.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nBtesla_api/protobuf/energy_device/v1/energy_accumulation_type.proto\x12\x1ctesla.proto.energy_device.v1*\xaf\x01\n\x16\x45nergyAccumulationType\x12$\n ENERGY_ACCUMULATION_TYPE_INVALID\x10\x00\x12%\n!ENERGY_ACCUMULATION_TYPE_LIFETIME\x10\x01\x12\"\n\x1e\x45NERGY_ACCUMULATION_TYPE_TODAY\x10\x02\x12$\n ENERGY_ACCUMULATION_TYPE_SESSION\x10\x03\x42\x8a\x01\n$com.tesla.generated.energy_device.v1B\x16\x45nergyAccumulationTypeZJgithub.com/teslamotors/energy_device/pkg/protocol/protobuf/energydevice/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tesla_api.protobuf.energy_device.v1.energy_accumulation_type_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n$com.tesla.generated.energy_device.v1B\026EnergyAccumulationTypeZJgithub.com/teslamotors/energy_device/pkg/protocol/protobuf/energydevice/v1'
  _globals['_ENERGYACCUMULATIONTYPE']._serialized_start=101
  _globals['_ENERGYACCUMULATIONTYPE']._serialized_end=276
# @@protoc_insertion_point(module_scope)
