# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tesla_api/protobuf/energy_device/v1/inst_ac_measurement.proto
# Protobuf Python Version: 6.33.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    0,
    '',
    'tesla_api/protobuf/energy_device/v1/inst_ac_measurement.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n=tesla_api/protobuf/energy_device/v1/inst_ac_measurement.proto\x12\x1ctesla.proto.energy_device.v1\x1a\x1egoogle/protobuf/wrappers.proto\"\x96\x02\n\x11InstACMeasurement\x12\x14\n\x0cvoltage_vrms\x18\x01 \x01(\x02\x12\x14\n\x0c\x66requency_hz\x18\x02 \x01(\x02\x12\x31\n\x0c\x63urrent_arms\x18\x03 \x01(\x0b\x32\x1b.google.protobuf.FloatValue\x12\x31\n\x0creal_power_w\x18\x04 \x01(\x0b\x32\x1b.google.protobuf.FloatValue\x12\x37\n\x12reactive_power_var\x18\x05 \x01(\x0b\x32\x1b.google.protobuf.FloatValue\x12\x36\n\x11\x61pparent_power_va\x18\x06 \x01(\x0b\x32\x1b.google.protobuf.FloatValueB\x85\x01\n$com.tesla.generated.energy_device.v1B\x11InstACMeasurementZJgithub.com/teslamotors/energy_device/pkg/protocol/protobuf/energydevice/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tesla_api.protobuf.energy_device.v1.inst_ac_measurement_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n$com.tesla.generated.energy_device.v1B\021InstACMeasurementZJgithub.com/teslamotors/energy_device/pkg/protocol/protobuf/energydevice/v1'
  _globals['_INSTACMEASUREMENT']._serialized_start=128
  _globals['_INSTACMEASUREMENT']._serialized_end=406
# @@protoc_insertion_point(module_scope)
