# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tesla_api/protobuf/energy_device/v1/intra_site_service_type.proto
# Protobuf Python Version: 6.33.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    0,
    '',
    'tesla_api/protobuf/energy_device/v1/intra_site_service_type.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nAtesla_api/protobuf/energy_device/v1/intra_site_service_type.proto*\xd1\x01\n\x14IntraSiteServiceType\x12#\n\x1fINTRA_SITE_SERVICE_TYPE_INVALID\x10\x00\x12.\n*INTRA_SITE_SERVICE_TYPE_MULTI_PW3_FOLLOWER\x10\x01\x12\x34\n0INTRA_SITE_SERVICE_TYPE_WC_LOAD_SHARING_FOLLOWER\x10\x02\x12.\n*INTRA_SITE_SERVICE_TYPE_WC_CURRENT_CONTROL\x10\x03')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tesla_api.protobuf.energy_device.v1.intra_site_service_type_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INTRASITESERVICETYPE']._serialized_start=70
  _globals['_INTRASITESERVICETYPE']._serialized_end=279
# @@protoc_insertion_point(module_scope)
