# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tesla_api/protobuf/energy_device/v1/locally_available_package.proto
# Protobuf Python Version: 6.33.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    0,
    '',
    'tesla_api/protobuf/energy_device/v1/locally_available_package.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nCtesla_api/protobuf/energy_device/v1/locally_available_package.proto\x12\x1ctesla.proto.energy_device.v1\"a\n\x17LocallyAvailablePackage\x12\x12\n\npackage_id\x18\x01 \x01(\x04\x12\x19\n\x11package_signature\x18\x02 \x01(\x0c\x12\x17\n\x0f\x66ile_size_bytes\x18\x03 \x01(\x04\x42\x8b\x01\n$com.tesla.generated.energy_device.v1B\x17LocallyAvailablePackageZJgithub.com/teslamotors/energy_device/pkg/protocol/protobuf/energydevice/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tesla_api.protobuf.energy_device.v1.locally_available_package_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n$com.tesla.generated.energy_device.v1B\027LocallyAvailablePackageZJgithub.com/teslamotors/energy_device/pkg/protocol/protobuf/energydevice/v1'
  _globals['_LOCALLYAVAILABLEPACKAGE']._serialized_start=101
  _globals['_LOCALLYAVAILABLEPACKAGE']._serialized_end=198
# @@protoc_insertion_point(module_scope)
