# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tesla_api/protobuf/energy_device/v1/message_envelope.proto
# Protobuf Python Version: 6.33.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    0,
    '',
    'tesla_api/protobuf/energy_device/v1/message_envelope.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tesla_api.protobuf.energy_device.v1 import authorization_messages_pb2 as tesla__api_dot_protobuf_dot_energy__device_dot_v1_dot_authorization__messages__pb2
from tesla_api.protobuf.energy_device.v1 import common_messages_pb2 as tesla__api_dot_protobuf_dot_energy__device_dot_v1_dot_common__messages__pb2
from tesla_api.protobuf.energy_device.v1 import delivery_channel_pb2 as tesla__api_dot_protobuf_dot_energy__device_dot_v1_dot_delivery__channel__pb2
from tesla_api.protobuf.energy_device.v1 import participant_pb2 as tesla__api_dot_protobuf_dot_energy__device_dot_v1_dot_participant__pb2
from tesla_api.protobuf.energy_device.v1 import teg_messages_pb2 as tesla__api_dot_protobuf_dot_energy__device_dot_v1_dot_teg__messages__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n:tesla_api/protobuf/energy_device/v1/message_envelope.proto\x12\x1ctesla.proto.energy_device.v1\x1a@tesla_api/protobuf/energy_device/v1/authorization_messages.proto\x1a\x39tesla_api/protobuf/energy_device/v1/common_messages.proto\x1a:tesla_api/protobuf/energy_device/v1/delivery_channel.proto\x1a\x35tesla_api/protobuf/energy_device/v1/participant.proto\x1a\x36tesla_api/protobuf/energy_device/v1/teg_messages.proto\"\xac\x03\n\x0fMessageEnvelope\x12G\n\x10\x64\x65livery_channel\x18\x01 \x01(\x0e\x32-.tesla.proto.energy_device.v1.DeliveryChannel\x12\x39\n\x06sender\x18\x02 \x01(\x0b\x32).tesla.proto.energy_device.v1.Participant\x12<\n\trecipient\x18\x03 \x01(\x0b\x32).tesla.proto.energy_device.v1.Participant\x12>\n\x06\x63ommon\x18\x04 \x01(\x0b\x32,.tesla.proto.energy_device.v1.CommonMessagesH\x00\x12\x38\n\x03teg\x18\x05 \x01(\x0b\x32).tesla.proto.energy_device.v1.TEGMessagesH\x00\x12L\n\rauthorization\x18\x0c \x01(\x0b\x32\x33.tesla.proto.energy_device.v1.AuthorizationMessagesH\x00\x42\t\n\x07payloadJ\x04\x08\x07\x10\x08\x42\x83\x01\n$com.tesla.generated.energy_device.v1B\x0fMessageEnvelopeZJgithub.com/teslamotors/energy_device/pkg/protocol/protobuf/energydevice/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tesla_api.protobuf.energy_device.v1.message_envelope_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n$com.tesla.generated.energy_device.v1B\017MessageEnvelopeZJgithub.com/teslamotors/energy_device/pkg/protocol/protobuf/energydevice/v1'
  _globals['_MESSAGEENVELOPE']._serialized_start=389
  _globals['_MESSAGEENVELOPE']._serialized_end=817
# @@protoc_insertion_point(module_scope)
