# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tesla_api/protobuf/energy_device/v1/network_connectivity_status.proto
# Protobuf Python Version: 6.33.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    0,
    '',
    'tesla_api/protobuf/energy_device/v1/network_connectivity_status.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from tesla_api.protobuf.energy_device.v1 import rssi_pb2 as tesla__api_dot_protobuf_dot_energy__device_dot_v1_dot_rssi__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nEtesla_api/protobuf/energy_device/v1/network_connectivity_status.proto\x12\x1ctesla.proto.energy_device.v1\x1a\x1egoogle/protobuf/wrappers.proto\x1a.tesla_api/protobuf/energy_device/v1/rssi.proto\"\xc8\x01\n\x19NetworkConnectivityStatus\x12\x1a\n\x12\x63onnected_physical\x18\x01 \x01(\x08\x12\x1a\n\x12\x63onnected_internet\x18\x02 \x01(\x08\x12\x17\n\x0f\x63onnected_tesla\x18\x03 \x01(\x08\x12\x30\n\x04rssi\x18\x04 \x01(\x0b\x32\".tesla.proto.energy_device.v1.Rssi\x12(\n\x03snr\x18\x05 \x01(\x0b\x32\x1b.google.protobuf.Int32ValueB\x8d\x01\n$com.tesla.generated.energy_device.v1B\x19NetworkConnectivityStatusZJgithub.com/teslamotors/energy_device/pkg/protocol/protobuf/energydevice/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tesla_api.protobuf.energy_device.v1.network_connectivity_status_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n$com.tesla.generated.energy_device.v1B\031NetworkConnectivityStatusZJgithub.com/teslamotors/energy_device/pkg/protocol/protobuf/energydevice/v1'
  _globals['_NETWORKCONNECTIVITYSTATUS']._serialized_start=184
  _globals['_NETWORKCONNECTIVITYSTATUS']._serialized_end=384
# @@protoc_insertion_point(module_scope)
