# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tesla_api/protobuf/energy_device/v1/network_device_state_reason.proto
# Protobuf Python Version: 6.33.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    0,
    '',
    'tesla_api/protobuf/energy_device/v1/network_device_state_reason.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nEtesla_api/protobuf/energy_device/v1/network_device_state_reason.proto*\x91\x06\n\x18NetworkDeviceStateReason\x12\'\n#NETWORK_DEVICE_STATE_REASON_INVALID\x10\x00\x12$\n NETWORK_DEVICE_STATE_REASON_NONE\x10\x01\x12-\n)NETWORK_DEVICE_STATE_REASON_CONFIG_FAILED\x10\x02\x12+\n\'NETWORK_DEVICE_STATE_REASON_DHCP_FAILED\x10\x03\x12\x34\n0NETWORK_DEVICE_STATE_REASON_IP_ADDRESS_DUPLICATE\x10\x04\x12\x31\n-NETWORK_DEVICE_STATE_REASON_IP_CONFIG_EXPIRED\x10\x05\x12\x35\n1NETWORK_DEVICE_STATE_REASON_IP_CONFIG_UNAVAILABLE\x10\x06\x12\x35\n1NETWORK_DEVICE_STATE_REASON_IP_METHOD_UNSUPPORTED\x10\x07\x12.\n*NETWORK_DEVICE_STATE_REASON_NEW_ACTIVATION\x10\x08\x12*\n&NETWORK_DEVICE_STATE_REASON_NO_SECRETS\x10\t\x12*\n&NETWORK_DEVICE_STATE_REASON_PPP_FAILED\x10\n\x12.\n*NETWORK_DEVICE_STATE_REASON_SSID_NOT_FOUND\x10\x0b\x12\x31\n-NETWORK_DEVICE_STATE_REASON_SIM_PIN_INCORRECT\x10\x0c\x12\x31\n-NETWORK_DEVICE_STATE_REASON_SUPPLICANT_FAILED\x10\r\x12\'\n#NETWORK_DEVICE_STATE_REASON_REMOVED\x10\x0e\x12,\n(NETWORK_DEVICE_STATE_REASON_MODEM_FAILED\x10\x0f')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tesla_api.protobuf.energy_device.v1.network_device_state_reason_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NETWORKDEVICESTATEREASON']._serialized_start=74
  _globals['_NETWORKDEVICESTATEREASON']._serialized_end=859
# @@protoc_insertion_point(module_scope)
