# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tesla_api/protobuf/energy_device/v1/network_interface_ipv4_config.proto
# Protobuf Python Version: 6.33.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    0,
    '',
    'tesla_api/protobuf/energy_device/v1/network_interface_ipv4_config.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nGtesla_api/protobuf/energy_device/v1/network_interface_ipv4_config.proto\x12\x1ctesla.proto.energy_device.v1\"|\n\x1aNetworkInterfaceIPv4Config\x12\x14\n\x0c\x64hcp_enabled\x18\x02 \x01(\x08\x12\x0f\n\x07\x61\x64\x64ress\x18\x03 \x01(\x07\x12\x13\n\x0bsubnet_mask\x18\x04 \x01(\x07\x12\x0f\n\x07gateway\x18\x05 \x01(\x07\x12\x0b\n\x03\x64ns\x18\x06 \x03(\x07J\x04\x08\x01\x10\x02\x42\x8e\x01\n$com.tesla.generated.energy_device.v1B\x1aNetworkInterfaceIPv4ConfigZJgithub.com/teslamotors/energy_device/pkg/protocol/protobuf/energydevice/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tesla_api.protobuf.energy_device.v1.network_interface_ipv4_config_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n$com.tesla.generated.energy_device.v1B\032NetworkInterfaceIPv4ConfigZJgithub.com/teslamotors/energy_device/pkg/protocol/protobuf/energydevice/v1'
  _globals['_NETWORKINTERFACEIPV4CONFIG']._serialized_start=105
  _globals['_NETWORKINTERFACEIPV4CONFIG']._serialized_end=229
# @@protoc_insertion_point(module_scope)
