# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tesla_api/protobuf/energy_device/v1/network_device_state.proto
# Protobuf Python Version: 6.33.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    0,
    '',
    'tesla_api/protobuf/energy_device/v1/network_device_state.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n>tesla_api/protobuf/energy_device/v1/network_device_state.proto*\xd4\x02\n\x12NetworkDeviceState\x12 \n\x1cNETWORK_DEVICE_STATE_INVALID\x10\x00\x12\"\n\x1eNETWORK_DEVICE_STATE_UNMANAGED\x10\x01\x12$\n NETWORK_DEVICE_STATE_UNAVAILABLE\x10\x02\x12\x1d\n\x19NETWORK_DEVICE_STATE_IDLE\x10\x03\x12$\n NETWORK_DEVICE_STATE_ASSOCIATION\x10\x04\x12&\n\"NETWORK_DEVICE_STATE_CONFIGURATION\x10\x05\x12\x1e\n\x1aNETWORK_DEVICE_STATE_READY\x10\x06\x12#\n\x1fNETWORK_DEVICE_STATE_DISCONNECT\x10\x07\x12 \n\x1cNETWORK_DEVICE_STATE_FAILURE\x10\x08')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tesla_api.protobuf.energy_device.v1.network_device_state_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NETWORKDEVICESTATE']._serialized_start=67
  _globals['_NETWORKDEVICESTATE']._serialized_end=407
# @@protoc_insertion_point(module_scope)
