# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tesla_api/protobuf/energy_device/v1/network_interface.proto
# Protobuf Python Version: 6.33.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    0,
    '',
    'tesla_api/protobuf/energy_device/v1/network_interface.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tesla_api.protobuf.energy_device.v1 import network_connectivity_status_pb2 as tesla__api_dot_protobuf_dot_energy__device_dot_v1_dot_network__connectivity__status__pb2
from tesla_api.protobuf.energy_device.v1 import network_interface_ipv4_config_pb2 as tesla__api_dot_protobuf_dot_energy__device_dot_v1_dot_network__interface__ipv4__config__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n;tesla_api/protobuf/energy_device/v1/network_interface.proto\x12\x1ctesla.proto.energy_device.v1\x1a\x45tesla_api/protobuf/energy_device/v1/network_connectivity_status.proto\x1aGtesla_api/protobuf/energy_device/v1/network_interface_ipv4_config.proto\"\xf3\x01\n\x10NetworkInterface\x12\x13\n\x0bmac_address\x18\x01 \x01(\x0c\x12\x0f\n\x07\x65nabled\x18\x02 \x01(\x08\x12\x14\n\x0c\x61\x63tive_route\x18\x03 \x01(\x08\x12M\n\x0bipv4_config\x18\x04 \x01(\x0b\x32\x38.tesla.proto.energy_device.v1.NetworkInterfaceIPv4Config\x12T\n\x13\x63onnectivity_status\x18\x05 \x01(\x0b\x32\x37.tesla.proto.energy_device.v1.NetworkConnectivityStatusB\x84\x01\n$com.tesla.generated.energy_device.v1B\x10NetworkInterfaceZJgithub.com/teslamotors/energy_device/pkg/protocol/protobuf/energydevice/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tesla_api.protobuf.energy_device.v1.network_interface_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n$com.tesla.generated.energy_device.v1B\020NetworkInterfaceZJgithub.com/teslamotors/energy_device/pkg/protocol/protobuf/energydevice/v1'
  _globals['_NETWORKINTERFACE']._serialized_start=238
  _globals['_NETWORKINTERFACE']._serialized_end=481
# @@protoc_insertion_point(module_scope)
