# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tesla_api/protobuf/energy_device/v1/server_staged_package.proto
# Protobuf Python Version: 6.33.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    0,
    '',
    'tesla_api/protobuf/energy_device/v1/server_staged_package.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tesla_api.protobuf.energy_device.v1 import firmware_version_pb2 as tesla__api_dot_protobuf_dot_energy__device_dot_v1_dot_firmware__version__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n?tesla_api/protobuf/energy_device/v1/server_staged_package.proto\x12\x1ctesla.proto.energy_device.v1\x1a:tesla_api/protobuf/energy_device/v1/firmware_version.proto\"\xa8\x01\n\x13ServerStagedPackage\x12\x14\n\x0c\x64ownload_url\x18\x01 \x01(\t\x12\x12\n\npackage_id\x18\x02 \x01(\x04\x12\x19\n\x11package_signature\x18\x03 \x01(\x0c\x12L\n\x15server_staged_version\x18\x04 \x01(\x0b\x32-.tesla.proto.energy_device.v1.FirmwareVersionB\x87\x01\n$com.tesla.generated.energy_device.v1B\x13ServerStagedPackageZJgithub.com/teslamotors/energy_device/pkg/protocol/protobuf/energydevice/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tesla_api.protobuf.energy_device.v1.server_staged_package_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n$com.tesla.generated.energy_device.v1B\023ServerStagedPackageZJgithub.com/teslamotors/energy_device/pkg/protocol/protobuf/energydevice/v1'
  _globals['_SERVERSTAGEDPACKAGE']._serialized_start=158
  _globals['_SERVERSTAGEDPACKAGE']._serialized_end=326
# @@protoc_insertion_point(module_scope)
