# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tesla_api/protobuf/energy_device/v1/teg_messages.proto
# Protobuf Python Version: 6.33.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    0,
    '',
    'tesla_api/protobuf/energy_device/v1/teg_messages.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tesla_api.protobuf.energy_device.v1 import teg_api_cancel_manual_backup_event_request_pb2 as tesla__api_dot_protobuf_dot_energy__device_dot_v1_dot_teg__api__cancel__manual__backup__event__request__pb2
from tesla_api.protobuf.energy_device.v1 import teg_api_cancel_manual_backup_event_response_pb2 as tesla__api_dot_protobuf_dot_energy__device_dot_v1_dot_teg__api__cancel__manual__backup__event__response__pb2
from tesla_api.protobuf.energy_device.v1 import teg_api_get_backup_events_request_pb2 as tesla__api_dot_protobuf_dot_energy__device_dot_v1_dot_teg__api__get__backup__events__request__pb2
from tesla_api.protobuf.energy_device.v1 import teg_api_get_backup_events_response_pb2 as tesla__api_dot_protobuf_dot_energy__device_dot_v1_dot_teg__api__get__backup__events__response__pb2
from tesla_api.protobuf.energy_device.v1 import teg_api_schedule_manual_backup_event_request_pb2 as tesla__api_dot_protobuf_dot_energy__device_dot_v1_dot_teg__api__schedule__manual__backup__event__request__pb2
from tesla_api.protobuf.energy_device.v1 import teg_api_schedule_manual_backup_event_response_pb2 as tesla__api_dot_protobuf_dot_energy__device_dot_v1_dot_teg__api__schedule__manual__backup__event__response__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n6tesla_api/protobuf/energy_device/v1/teg_messages.proto\x12\x1ctesla.proto.energy_device.v1\x1aTtesla_api/protobuf/energy_device/v1/teg_api_cancel_manual_backup_event_request.proto\x1aUtesla_api/protobuf/energy_device/v1/teg_api_cancel_manual_backup_event_response.proto\x1aKtesla_api/protobuf/energy_device/v1/teg_api_get_backup_events_request.proto\x1aLtesla_api/protobuf/energy_device/v1/teg_api_get_backup_events_response.proto\x1aVtesla_api/protobuf/energy_device/v1/teg_api_schedule_manual_backup_event_request.proto\x1aWtesla_api/protobuf/energy_device/v1/teg_api_schedule_manual_backup_event_response.proto\"\xb0\x05\n\x0bTEGMessages\x12t\n$schedule_manual_backup_event_request\x18- \x01(\x0b\x32\x44.tesla.proto.energy_device.v1.TEGAPIScheduleManualBackupEventRequestH\x00\x12v\n%schedule_manual_backup_event_response\x18. \x01(\x0b\x32\x45.tesla.proto.energy_device.v1.TEGAPIScheduleManualBackupEventResponseH\x00\x12p\n\"cancel_manual_backup_event_request\x18/ \x01(\x0b\x32\x42.tesla.proto.energy_device.v1.TEGAPICancelManualBackupEventRequestH\x00\x12r\n#cancel_manual_backup_event_response\x18\x30 \x01(\x0b\x32\x43.tesla.proto.energy_device.v1.TEGAPICancelManualBackupEventResponseH\x00\x12_\n\x19get_backup_events_request\x18\x31 \x01(\x0b\x32:.tesla.proto.energy_device.v1.TEGAPIGetBackupEventsRequestH\x00\x12\x61\n\x1aget_backup_events_response\x18\x32 \x01(\x0b\x32;.tesla.proto.energy_device.v1.TEGAPIGetBackupEventsResponseH\x00\x42\t\n\x07messageB\x7f\n$com.tesla.generated.energy_device.v1B\x0bTEGMessagesZJgithub.com/teslamotors/energy_device/pkg/protocol/protobuf/energydevice/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tesla_api.protobuf.energy_device.v1.teg_messages_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n$com.tesla.generated.energy_device.v1B\013TEGMessagesZJgithub.com/teslamotors/energy_device/pkg/protocol/protobuf/energydevice/v1'
  _globals['_TEGMESSAGES']._serialized_start=594
  _globals['_TEGMESSAGES']._serialized_end=1282
# @@protoc_insertion_point(module_scope)
