# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tesla_api/protobuf/energy_device/v1/teg_api_get_backup_events_response.proto
# Protobuf Python Version: 6.33.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    0,
    '',
    'tesla_api/protobuf/energy_device/v1/teg_api_get_backup_events_response.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tesla_api.protobuf.energy_device.v1 import backup_event_pb2 as tesla__api_dot_protobuf_dot_energy__device_dot_v1_dot_backup__event__pb2
from tesla_api.protobuf.energy_device.v1 import manual_backup_event_pb2 as tesla__api_dot_protobuf_dot_energy__device_dot_v1_dot_manual__backup__event__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nLtesla_api/protobuf/energy_device/v1/teg_api_get_backup_events_response.proto\x12\x1ctesla.proto.energy_device.v1\x1a\x36tesla_api/protobuf/energy_device/v1/backup_event.proto\x1a=tesla_api/protobuf/energy_device/v1/manual_backup_event.proto\"\xaf\x01\n\x1dTEGAPIGetBackupEventsResponse\x12L\n\x13manual_backup_event\x18\x01 \x01(\x0b\x32/.tesla.proto.energy_device.v1.ManualBackupEvent\x12@\n\rbackup_events\x18\x02 \x03(\x0b\x32).tesla.proto.energy_device.v1.BackupEventB\x91\x01\n$com.tesla.generated.energy_device.v1B\x1dTEGAPIGetBackupEventsResponseZJgithub.com/teslamotors/energy_device/pkg/protocol/protobuf/energydevice/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tesla_api.protobuf.energy_device.v1.teg_api_get_backup_events_response_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n$com.tesla.generated.energy_device.v1B\035TEGAPIGetBackupEventsResponseZJgithub.com/teslamotors/energy_device/pkg/protocol/protobuf/energydevice/v1'
  _globals['_TEGAPIGETBACKUPEVENTSRESPONSE']._serialized_start=230
  _globals['_TEGAPIGETBACKUPEVENTSRESPONSE']._serialized_end=405
# @@protoc_insertion_point(module_scope)
