# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tesla_api/protobuf/energy_device/v1/teg_api_schedule_manual_backup_event_request.proto
# Protobuf Python Version: 6.33.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    0,
    '',
    'tesla_api/protobuf/energy_device/v1/teg_api_schedule_manual_backup_event_request.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tesla_api.protobuf.energy_device.v1 import control_event_scheduling_info_pb2 as tesla__api_dot_protobuf_dot_energy__device_dot_v1_dot_control__event__scheduling__info__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nVtesla_api/protobuf/energy_device/v1/teg_api_schedule_manual_backup_event_request.proto\x12\x1ctesla.proto.energy_device.v1\x1aGtesla_api/protobuf/energy_device/v1/control_event_scheduling_info.proto\"{\n&TEGAPIScheduleManualBackupEventRequest\x12Q\n\x0fscheduling_info\x18\x01 \x01(\x0b\x32\x38.tesla.proto.energy_device.v1.ControlEventSchedulingInfoB\x9a\x01\n$com.tesla.generated.energy_device.v1B&TEGAPIScheduleManualBackupEventRequestZJgithub.com/teslamotors/energy_device/pkg/protocol/protobuf/energydevice/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tesla_api.protobuf.energy_device.v1.teg_api_schedule_manual_backup_event_request_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n$com.tesla.generated.energy_device.v1B&TEGAPIScheduleManualBackupEventRequestZJgithub.com/teslamotors/energy_device/pkg/protocol/protobuf/energydevice/v1'
  _globals['_TEGAPISCHEDULEMANUALBACKUPEVENTREQUEST']._serialized_start=193
  _globals['_TEGAPISCHEDULEMANUALBACKUPEVENTREQUEST']._serialized_end=316
# @@protoc_insertion_point(module_scope)
