# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tesla_api/protobuf/energy_device/v1/teg_device_type.proto
# Protobuf Python Version: 6.33.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    0,
    '',
    'tesla_api/protobuf/energy_device/v1/teg_device_type.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n9tesla_api/protobuf/energy_device/v1/teg_device_type.proto*\xfb\x02\n\rTEGDeviceType\x12\x1b\n\x17TEG_DEVICE_TYPE_INVALID\x10\x00\x12\x17\n\x13TEG_DEVICE_TYPE_SMC\x10\x01\x12 \n\x1cTEG_DEVICE_TYPE_HEC_GATEWAY1\x10\x02\x12 \n\x1cTEG_DEVICE_TYPE_TEG_GATEWAY2\x10\x03\x12%\n!TEG_DEVICE_TYPE_TEG_POWERWALLPLUS\x10\x04\x12\x1b\n\x17TEG_DEVICE_TYPE_TEG_MP1\x10\x05\x12$\n TEG_DEVICE_TYPE_TEG_SUPERCHARGER\x10\x06\x12#\n\x1fTEG_DEVICE_TYPE_TACO_POWERWALL3\x10\x07\x12\x1b\n\x17TEG_DEVICE_TYPE_TEG_PVI\x10\x08\x12\"\n\x1eTEG_DEVICE_TYPE_TACO_GATEWAY3V\x10\t\x12 \n\x1cTEG_DEVICE_TYPE_TACO_WALLBOX\x10\n')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tesla_api.protobuf.energy_device.v1.teg_device_type_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TEGDEVICETYPE']._serialized_start=62
  _globals['_TEGDEVICETYPE']._serialized_end=441
# @@protoc_insertion_point(module_scope)
