# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tesla_api/protobuf/energy_device/v1/wc_charge_schedule_charging_status.proto
# Protobuf Python Version: 6.33.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    0,
    '',
    'tesla_api/protobuf/energy_device/v1/wc_charge_schedule_charging_status.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nLtesla_api/protobuf/energy_device/v1/wc_charge_schedule_charging_status.proto\x12\x1ctesla.proto.energy_device.v1*\xb5\x03\n\x1eWCChargeScheduleChargingStatus\x12.\n*WC_CHARGE_SCHEDULE_CHARGING_STATUS_INVALID\x10\x00\x12<\n8WC_CHARGE_SCHEDULE_CHARGING_STATUS_UNCONFIGURED_DISABLED\x10\x01\x12\x35\n1WC_CHARGE_SCHEDULE_CHARGING_STATUS_CHARGE_BLOCKED\x10\x02\x12=\n9WC_CHARGE_SCHEDULE_CHARGING_STATUS_DELAYED_CHARGE_BLOCKED\x10\x03\x12\x35\n1WC_CHARGE_SCHEDULE_CHARGING_STATUS_CHARGE_ALLOWED\x10\x04\x12=\n9WC_CHARGE_SCHEDULE_CHARGING_STATUS_DELAYED_CHARGE_ALLOWED\x10\x05\x12\x39\n5WC_CHARGE_SCHEDULE_CHARGING_STATUS_VEHICLE_OVERRIDDEN\x10\x06\x42\x92\x01\n$com.tesla.generated.energy_device.v1B\x1eWCChargeScheduleChargingStatusZJgithub.com/teslamotors/energy-device/pkg/protocol/protobuf/energydevice/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tesla_api.protobuf.energy_device.v1.wc_charge_schedule_charging_status_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n$com.tesla.generated.energy_device.v1B\036WCChargeScheduleChargingStatusZJgithub.com/teslamotors/energy-device/pkg/protocol/protobuf/energydevice/v1'
  _globals['_WCCHARGESCHEDULECHARGINGSTATUS']._serialized_start=111
  _globals['_WCCHARGESCHEDULECHARGINGSTATUS']._serialized_end=548
# @@protoc_insertion_point(module_scope)
