# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tesla_api/protobuf/energy_device/v1/wc_charge_schedule_config_error.proto
# Protobuf Python Version: 6.33.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    0,
    '',
    'tesla_api/protobuf/energy_device/v1/wc_charge_schedule_config_error.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nItesla_api/protobuf/energy_device/v1/wc_charge_schedule_config_error.proto\x12\x1ctesla.proto.energy_device.v1*\xc3\x02\n\x1bWCChargeScheduleConfigError\x12+\n\'WC_CHARGE_SCHEDULE_CONFIG_ERROR_INVALID\x10\x00\x12(\n$WC_CHARGE_SCHEDULE_CONFIG_ERROR_NONE\x10\x01\x12\x30\n,WC_CHARGE_SCHEDULE_CONFIG_ERROR_NO_SITE_WIFI\x10\x02\x12/\n+WC_CHARGE_SCHEDULE_CONFIG_ERROR_NO_INTERNET\x10\x03\x12\x36\n2WC_CHARGE_SCHEDULE_CONFIG_ERROR_INVALID_PARAMETERS\x10\x04\x12\x32\n.WC_CHARGE_SCHEDULE_CONFIG_ERROR_INTERNAL_ERROR\x10\x05\x42\x8f\x01\n$com.tesla.generated.energy_device.v1B\x1bWCChargeScheduleConfigErrorZJgithub.com/teslamotors/energy-device/pkg/protocol/protobuf/energydevice/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tesla_api.protobuf.energy_device.v1.wc_charge_schedule_config_error_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n$com.tesla.generated.energy_device.v1B\033WCChargeScheduleConfigErrorZJgithub.com/teslamotors/energy-device/pkg/protocol/protobuf/energydevice/v1'
  _globals['_WCCHARGESCHEDULECONFIGERROR']._serialized_start=108
  _globals['_WCCHARGESCHEDULECONFIGERROR']._serialized_end=431
# @@protoc_insertion_point(module_scope)
