# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tesla_api/protobuf/energy_device/v1/wc_charge_schedule_day.proto
# Protobuf Python Version: 6.33.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    0,
    '',
    'tesla_api/protobuf/energy_device/v1/wc_charge_schedule_day.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n@tesla_api/protobuf/energy_device/v1/wc_charge_schedule_day.proto\x12\x1ctesla.proto.energy_device.v1*\xb6\x02\n\x13WCChargeScheduleDay\x12\"\n\x1eWC_CHARGE_SCHEDULE_DAY_INVALID\x10\x00\x12!\n\x1dWC_CHARGE_SCHEDULE_DAY_SUNDAY\x10\x01\x12!\n\x1dWC_CHARGE_SCHEDULE_DAY_MONDAY\x10\x02\x12\"\n\x1eWC_CHARGE_SCHEDULE_DAY_TUESDAY\x10\x04\x12$\n WC_CHARGE_SCHEDULE_DAY_WEDNESDAY\x10\x08\x12#\n\x1fWC_CHARGE_SCHEDULE_DAY_THURSDAY\x10\x10\x12!\n\x1dWC_CHARGE_SCHEDULE_DAY_FRIDAY\x10 \x12#\n\x1fWC_CHARGE_SCHEDULE_DAY_SATURDAY\x10@B\x87\x01\n$com.tesla.generated.energy_device.v1B\x13WCChargeScheduleDayZJgithub.com/teslamotors/energy-device/pkg/protocol/protobuf/energydevice/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tesla_api.protobuf.energy_device.v1.wc_charge_schedule_day_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n$com.tesla.generated.energy_device.v1B\023WCChargeScheduleDayZJgithub.com/teslamotors/energy-device/pkg/protocol/protobuf/energydevice/v1'
  _globals['_WCCHARGESCHEDULEDAY']._serialized_start=99
  _globals['_WCCHARGESCHEDULEDAY']._serialized_end=409
# @@protoc_insertion_point(module_scope)
