# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tesla_api/protobuf/energy_device/v1/wc_evse_not_ready_reason.proto
# Protobuf Python Version: 6.33.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    0,
    '',
    'tesla_api/protobuf/energy_device/v1/wc_evse_not_ready_reason.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nBtesla_api/protobuf/energy_device/v1/wc_evse_not_ready_reason.proto*\x91\x05\n\x14WCEvseNotReadyReason\x12$\n WC_EVSE_NOT_READY_REASON_INVALID\x10\x00\x12-\n)WC_EVSE_NOT_READY_REASON_COLD_LOAD_PICKUP\x10\x01\x12*\n&WC_EVSE_NOT_READY_REASON_HANDLE_BUTTON\x10\x02\x12)\n%WC_EVSE_NOT_READY_REASON_SESSION_AUTH\x10\x03\x12,\n(WC_EVSE_NOT_READY_REASON_FAULT_NO_CHARGE\x10\x04\x12*\n&WC_EVSE_NOT_READY_REASON_FAULT_STARTUP\x10\x05\x12*\n&WC_EVSE_NOT_READY_REASON_GMI_NO_CHARGE\x10\x06\x12+\n\'WC_EVSE_NOT_READY_REASON_PILOT_NOT_CONN\x10\x07\x12,\n(WC_EVSE_NOT_READY_REASON_CONFIG_NOT_RECV\x10\x08\x12\x31\n-WC_EVSE_NOT_READY_REASON_LOAD_SHARE_NO_CHARGE\x10\t\x12+\n\'WC_EVSE_NOT_READY_REASON_OCPP_NO_CHARGE\x10\n\x12\x30\n,WC_EVSE_NOT_READY_REASON_ACCESS_CONTROL_LIST\x10\x0b\x12(\n$WC_EVSE_NOT_READY_REASON_PAY_PER_USE\x10\x0c\x12\x30\n,WC_EVSE_NOT_READY_REASON_THIRD_PARTY_VEHICLE\x10\r')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tesla_api.protobuf.energy_device.v1.wc_evse_not_ready_reason_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WCEVSENOTREADYREASON']._serialized_start=71
  _globals['_WCEVSENOTREADYREASON']._serialized_end=728
# @@protoc_insertion_point(module_scope)
