# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tesla_api/protobuf/energy_device/v1/wc_fault_status_state.proto
# Protobuf Python Version: 6.33.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    0,
    '',
    'tesla_api/protobuf/energy_device/v1/wc_fault_status_state.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n?tesla_api/protobuf/energy_device/v1/wc_fault_status_state.proto\x12\x1ctesla.proto.energy_device.v1*\x99\x03\n\x12WCFaultStatusState\x12!\n\x1dWC_FAULT_STATUS_STATE_INVALID\x10\x00\x12!\n\x1dWC_FAULT_STATUS_STATE_STARTUP\x10\x01\x12\x1f\n\x1bWC_FAULT_STATUS_STATE_READY\x10\x02\x12(\n$WC_FAULT_STATUS_STATE_CRITICAL_FAULT\x10\x03\x12,\n(WC_FAULT_STATUS_STATE_NON_CRITICAL_FAULT\x10\x04\x12\'\n#WC_FAULT_STATUS_STATE_RETRY_PENDING\x10\x05\x12!\n\x1dWC_FAULT_STATUS_STATE_LOCKOUT\x10\x06\x12\"\n\x1eWC_FAULT_STATUS_STATE_FOLDBACK\x10\x07\x12\"\n\x1eWC_FAULT_STATUS_STATE_CHARGING\x10\x08\x12\x30\n,WC_FAULT_STATUS_STATE_CONFIGURATION_REQUIRED\x10\tB\x86\x01\n$com.tesla.generated.energy_device.v1B\x12WCFaultStatusStateZJgithub.com/teslamotors/energy-device/pkg/protocol/protobuf/energydevice/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tesla_api.protobuf.energy_device.v1.wc_fault_status_state_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n$com.tesla.generated.energy_device.v1B\022WCFaultStatusStateZJgithub.com/teslamotors/energy-device/pkg/protocol/protobuf/energydevice/v1'
  _globals['_WCFAULTSTATUSSTATE']._serialized_start=98
  _globals['_WCFAULTSTATUSSTATE']._serialized_end=507
# @@protoc_insertion_point(module_scope)
