# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tesla_api/protobuf/energy_device/v1/wc_load_sharing_network_charging_inhibitor.proto
# Protobuf Python Version: 6.33.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    0,
    '',
    'tesla_api/protobuf/energy_device/v1/wc_load_sharing_network_charging_inhibitor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nTtesla_api/protobuf/energy_device/v1/wc_load_sharing_network_charging_inhibitor.proto\x12\x1ctesla.proto.energy_device.v1*\xa5\x02\n%WCLoadSharingNetworkChargingInhibitor\x12\x36\n2WC_LOAD_SHARING_NETWORK_CHARGING_INHIBITOR_INVALID\x10\x00\x12\x43\n?WC_LOAD_SHARING_NETWORK_CHARGING_INHIBITOR_INSUFFICIENT_CURRENT\x10\x01\x12\x43\n?WC_LOAD_SHARING_NETWORK_CHARGING_INHIBITOR_INSUFFICIENT_DEVICES\x10\x02\x12:\n6WC_LOAD_SHARING_NETWORK_CHARGING_INHIBITOR_DEVICES_MIA\x10\x03\x42\x99\x01\n$com.tesla.generated.energy_device.v1B%WCLoadSharingNetworkChargingInhibitorZJgithub.com/teslamotors/energy-device/pkg/protocol/protobuf/energydevice/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tesla_api.protobuf.energy_device.v1.wc_load_sharing_network_charging_inhibitor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n$com.tesla.generated.energy_device.v1B%WCLoadSharingNetworkChargingInhibitorZJgithub.com/teslamotors/energy-device/pkg/protocol/protobuf/energydevice/v1'
  _globals['_WCLOADSHARINGNETWORKCHARGINGINHIBITOR']._serialized_start=119
  _globals['_WCLOADSHARINGNETWORKCHARGINGINHIBITOR']._serialized_end=412
# @@protoc_insertion_point(module_scope)
