# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tesla_api/protobuf/energy_device/v1/wc_ocpp_status.proto
# Protobuf Python Version: 6.33.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    0,
    '',
    'tesla_api/protobuf/energy_device/v1/wc_ocpp_status.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n8tesla_api/protobuf/energy_device/v1/wc_ocpp_status.proto*\xb5\x02\n\x0cWCOcppStatus\x12\x1a\n\x16WC_OCPP_STATUS_INVALID\x10\x00\x12\x1f\n\x1bWC_OCPP_STATUS_UNCONFIGURED\x10\x01\x12+\n\'WC_OCPP_STATUS_INCOMPLETE_CONFIGURATION\x10\x02\x12&\n\"WC_OCPP_STATUS_CONFIGURED_DISABLED\x10\x03\x12%\n!WC_OCPP_STATUS_CONFIGURED_ENABLED\x10\x04\x12/\n+WC_OCPP_STATUS_CONFIGURED_ENABLED_CONNECTED\x10\x05\x12;\n7WC_OCPP_STATUS_CONFIGURED_ENABLED_INVALID_CONFIGURATION\x10\x06')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tesla_api.protobuf.energy_device.v1.wc_ocpp_status_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WCOCPPSTATUS']._serialized_start=61
  _globals['_WCOCPPSTATUS']._serialized_end=370
# @@protoc_insertion_point(module_scope)
