# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tesla_api/protobuf/energy_device/v1/wc_tesla_vehicle_drive_type.proto
# Protobuf Python Version: 6.33.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    0,
    '',
    'tesla_api/protobuf/energy_device/v1/wc_tesla_vehicle_drive_type.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nEtesla_api/protobuf/energy_device/v1/wc_tesla_vehicle_drive_type.proto\x12\x1ctesla.proto.energy_device.v1*\xa0\x02\n\x17WCTeslaVehicleDriveType\x12\'\n#WC_TESLA_VEHICLE_DRIVE_TYPE_INVALID\x10\x00\x12\x35\n1WC_TESLA_VEHICLE_DRIVE_TYPE_SINGLE_MOTOR_STANDARD\x10\x01\x12\x38\n4WC_TESLA_VEHICLE_DRIVE_TYPE_SINGLE_MOTOR_PERFORMANCE\x10\x02\x12\x33\n/WC_TESLA_VEHICLE_DRIVE_TYPE_DUAL_MOTOR_STANDARD\x10\x03\x12\x36\n2WC_TESLA_VEHICLE_DRIVE_TYPE_DUAL_MOTOR_PERFORMANCE\x10\x04\x42\x8b\x01\n$com.tesla.generated.energy_device.v1B\x17WCTeslaVehicleDriveTypeZJgithub.com/teslamotors/energy-device/pkg/protocol/protobuf/energydevice/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tesla_api.protobuf.energy_device.v1.wc_tesla_vehicle_drive_type_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n$com.tesla.generated.energy_device.v1B\027WCTeslaVehicleDriveTypeZJgithub.com/teslamotors/energy-device/pkg/protocol/protobuf/energydevice/v1'
  _globals['_WCTESLAVEHICLEDRIVETYPE']._serialized_start=104
  _globals['_WCTESLAVEHICLEDRIVETYPE']._serialized_end=392
# @@protoc_insertion_point(module_scope)
