# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tesla_api/protobuf/energy_device/v1/wifi_config.proto
# Protobuf Python Version: 6.33.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    0,
    '',
    'tesla_api/protobuf/energy_device/v1/wifi_config.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tesla_api.protobuf.energy_device.v1 import wifi_password_pb2 as tesla__api_dot_protobuf_dot_energy__device_dot_v1_dot_wifi__password__pb2
from tesla_api.protobuf.energy_device.v1 import wifi_network_security_type_pb2 as tesla__api_dot_protobuf_dot_energy__device_dot_v1_dot_wifi__network__security__type__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n5tesla_api/protobuf/energy_device/v1/wifi_config.proto\x12\x1ctesla.proto.energy_device.v1\x1a\x37tesla_api/protobuf/energy_device/v1/wifi_password.proto\x1a\x44tesla_api/protobuf/energy_device/v1/wifi_network_security_type.proto\"\xa6\x01\n\nWifiConfig\x12\x0c\n\x04ssid\x18\x01 \x01(\t\x12<\n\x08password\x18\x02 \x01(\x0b\x32*.tesla.proto.energy_device.v1.WifiPassword\x12L\n\rsecurity_type\x18\x03 \x01(\x0e\x32\x35.tesla.proto.energy_device.v1.WifiNetworkSecurityTypeB~\n$com.tesla.generated.energy_device.v1B\nWifiConfigZJgithub.com/teslamotors/energy_device/pkg/protocol/protobuf/energydevice/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tesla_api.protobuf.energy_device.v1.wifi_config_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n$com.tesla.generated.energy_device.v1B\nWifiConfigZJgithub.com/teslamotors/energy_device/pkg/protocol/protobuf/energydevice/v1'
  _globals['_WIFICONFIG']._serialized_start=215
  _globals['_WIFICONFIG']._serialized_end=381
# @@protoc_insertion_point(module_scope)
