# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tesla_api/protobuf/energy_device/v1/wifi_network.proto
# Protobuf Python Version: 6.33.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    0,
    '',
    'tesla_api/protobuf/energy_device/v1/wifi_network.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tesla_api.protobuf.energy_device.v1 import rssi_pb2 as tesla__api_dot_protobuf_dot_energy__device_dot_v1_dot_rssi__pb2
from tesla_api.protobuf.energy_device.v1 import wifi_network_security_type_pb2 as tesla__api_dot_protobuf_dot_energy__device_dot_v1_dot_wifi__network__security__type__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n6tesla_api/protobuf/energy_device/v1/wifi_network.proto\x12\x1ctesla.proto.energy_device.v1\x1a.tesla_api/protobuf/energy_device/v1/rssi.proto\x1a\x44tesla_api/protobuf/energy_device/v1/wifi_network_security_type.proto\"\xad\x01\n\x0bWifiNetwork\x12\x0c\n\x04ssid\x18\x01 \x01(\t\x12\x11\n\trssiValue\x18\x02 \x01(\x11\x12\x30\n\x04rssi\x18\x03 \x01(\x0b\x32\".tesla.proto.energy_device.v1.Rssi\x12K\n\x0csecurityType\x18\x04 \x01(\x0e\x32\x35.tesla.proto.energy_device.v1.WifiNetworkSecurityTypeB\x7f\n$com.tesla.generated.energy_device.v1B\x0bWifiNetworkZJgithub.com/teslamotors/energy_device/pkg/protocol/protobuf/energydevice/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tesla_api.protobuf.energy_device.v1.wifi_network_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n$com.tesla.generated.energy_device.v1B\013WifiNetworkZJgithub.com/teslamotors/energy_device/pkg/protocol/protobuf/energydevice/v1'
  _globals['_WIFINETWORK']._serialized_start=207
  _globals['_WIFINETWORK']._serialized_end=380
# @@protoc_insertion_point(module_scope)
