# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tesla_api/protobuf/universal_message/destination.proto
# Protobuf Python Version: 6.33.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    0,
    '',
    'tesla_api/protobuf/universal_message/destination.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tesla_api.protobuf.universal_message import domain_pb2 as tesla__api_dot_protobuf_dot_universal__message_dot_domain__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n6tesla_api/protobuf/universal_message/destination.proto\x12\x10UniversalMessage\x1a\x31tesla_api/protobuf/universal_message/domain.proto\"g\n\x0b\x44\x65stination\x12*\n\x06\x64omain\x18\x01 \x01(\x0e\x32\x18.UniversalMessage.DomainH\x00\x12\x19\n\x0frouting_address\x18\x02 \x01(\x0cH\x00\x42\x11\n\x0fsub_destinationB\x82\x01\n$com.tesla.generated.universalmessageB\x0b\x44\x65stinationZMgithub.com/teslamotors/vehicle_command/pkg/protocol/protobuf/universalmessageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tesla_api.protobuf.universal_message.destination_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n$com.tesla.generated.universalmessageB\013DestinationZMgithub.com/teslamotors/vehicle_command/pkg/protocol/protobuf/universalmessage'
  _globals['_DESTINATION']._serialized_start=127
  _globals['_DESTINATION']._serialized_end=230
# @@protoc_insertion_point(module_scope)
