# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tesla_api/protobuf/signatures/get_session_info_request.proto
# Protobuf Python Version: 6.33.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    0,
    '',
    'tesla_api/protobuf/signatures/get_session_info_request.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tesla_api.protobuf.signatures import key_identity_pb2 as tesla__api_dot_protobuf_dot_signatures_dot_key__identity__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n<tesla_api/protobuf/signatures/get_session_info_request.proto\x12\nSignatures\x1a\x30tesla_api/protobuf/signatures/key_identity.proto\"F\n\x15GetSessionInfoRequest\x12-\n\x0ckey_identity\x18\x01 \x01(\x0b\x32\x17.Signatures.KeyIdentityB\x80\x01\n\x1e\x63om.tesla.generated.signaturesB\x15GetSessionInfoRequestZGgithub.com/teslamotors/vehicle_command/pkg/protocol/protobuf/signaturesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tesla_api.protobuf.signatures.get_session_info_request_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\036com.tesla.generated.signaturesB\025GetSessionInfoRequestZGgithub.com/teslamotors/vehicle_command/pkg/protocol/protobuf/signatures'
  _globals['_GETSESSIONINFOREQUEST']._serialized_start=126
  _globals['_GETSESSIONINFOREQUEST']._serialized_end=196
# @@protoc_insertion_point(module_scope)
