# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tesla_api/protobuf/signatures/hmac_signature_data.proto
# Protobuf Python Version: 6.33.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    0,
    '',
    'tesla_api/protobuf/signatures/hmac_signature_data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n7tesla_api/protobuf/signatures/hmac_signature_data.proto\x12\nSignatures\" \n\x11HmacSignatureData\x12\x0b\n\x03tag\x18\x01 \x01(\x0c\x42|\n\x1e\x63om.tesla.generated.signaturesB\x11HmacSignatureDataZGgithub.com/teslamotors/vehicle_command/pkg/protocol/protobuf/signaturesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tesla_api.protobuf.signatures.hmac_signature_data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\036com.tesla.generated.signaturesB\021HmacSignatureDataZGgithub.com/teslamotors/vehicle_command/pkg/protocol/protobuf/signatures'
  _globals['_HMACSIGNATUREDATA']._serialized_start=71
  _globals['_HMACSIGNATUREDATA']._serialized_end=103
# @@protoc_insertion_point(module_scope)
