# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tesla_api/protobuf/signatures/hmac_personalized_signature_data.proto
# Protobuf Python Version: 6.33.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    0,
    '',
    'tesla_api/protobuf/signatures/hmac_personalized_signature_data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nDtesla_api/protobuf/signatures/hmac_personalized_signature_data.proto\x12\nSignatures\"`\n\x1dHmacPersonalizedSignatureData\x12\r\n\x05\x65poch\x18\x01 \x01(\x0c\x12\x0f\n\x07\x63ounter\x18\x02 \x01(\r\x12\x12\n\nexpires_at\x18\x03 \x01(\x07\x12\x0b\n\x03tag\x18\x04 \x01(\x0c\x42\x88\x01\n\x1e\x63om.tesla.generated.signaturesB\x1dHmacPersonalizedSignatureDataZGgithub.com/teslamotors/vehicle_command/pkg/protocol/protobuf/signaturesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tesla_api.protobuf.signatures.hmac_personalized_signature_data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\036com.tesla.generated.signaturesB\035HmacPersonalizedSignatureDataZGgithub.com/teslamotors/vehicle_command/pkg/protocol/protobuf/signatures'
  _globals['_HMACPERSONALIZEDSIGNATUREDATA']._serialized_start=84
  _globals['_HMACPERSONALIZEDSIGNATUREDATA']._serialized_end=180
# @@protoc_insertion_point(module_scope)
