# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tesla_api/protobuf/signatures/session_info.proto
# Protobuf Python Version: 6.33.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    0,
    '',
    'tesla_api/protobuf/signatures/session_info.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tesla_api.protobuf.signatures import session_info_status_pb2 as tesla__api_dot_protobuf_dot_signatures_dot_session__info__status__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0tesla_api/protobuf/signatures/session_info.proto\x12\nSignatures\x1a\x37tesla_api/protobuf/signatures/session_info_status.proto\"\x93\x01\n\x0bSessionInfo\x12\x0f\n\x07\x63ounter\x18\x01 \x01(\r\x12\x11\n\tpublicKey\x18\x02 \x01(\x0c\x12\r\n\x05\x65poch\x18\x03 \x01(\x0c\x12\x12\n\nclock_time\x18\x04 \x01(\x07\x12-\n\x06status\x18\x05 \x01(\x0e\x32\x1d.Signatures.SessionInfoStatus\x12\x0e\n\x06handle\x18\x06 \x01(\rBv\n\x1e\x63om.tesla.generated.signaturesB\x0bSessionInfoZGgithub.com/teslamotors/vehicle_command/pkg/protocol/protobuf/signaturesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tesla_api.protobuf.signatures.session_info_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\036com.tesla.generated.signaturesB\013SessionInfoZGgithub.com/teslamotors/vehicle_command/pkg/protocol/protobuf/signatures'
  _globals['_SESSIONINFO']._serialized_start=122
  _globals['_SESSIONINFO']._serialized_end=269
# @@protoc_insertion_point(module_scope)
