# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tesla_api/protobuf/universal_message/v1/domain.proto
# Protobuf Python Version: 6.33.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    0,
    '',
    'tesla_api/protobuf/universal_message/v1/domain.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n4tesla_api/protobuf/universal_message/v1/domain.proto\x12 tesla.proto.universal_message.v1*\x9f\x01\n\x06\x44omain\x12\x14\n\x10\x44OMAIN_BROADCAST\x10\x00\x12\x1b\n\x17\x44OMAIN_VEHICLE_SECURITY\x10\x02\x12\x17\n\x13\x44OMAIN_INFOTAINMENT\x10\x03\x12\x10\n\x0c\x44OMAIN_AUTHD\x10\x05\x12\x18\n\x14\x44OMAIN_ENERGY_DEVICE\x10\x07\x12\x1d\n\x19\x44OMAIN_ENERGY_DEVICE_AUTH\x10\x08\x42\x81\x01\n(com.tesla.generated.universal_message.v1B\x06\x44omainZMgithub.com/teslamotors/vehicle_command/pkg/protocol/protobuf/universalmessageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tesla_api.protobuf.universal_message.v1.domain_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n(com.tesla.generated.universal_message.v1B\006DomainZMgithub.com/teslamotors/vehicle_command/pkg/protocol/protobuf/universalmessage'
  _globals['_DOMAIN']._serialized_start=91
  _globals['_DOMAIN']._serialized_end=250
# @@protoc_insertion_point(module_scope)
