# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tesla_api/protobuf/universal_message/v1/message_status.proto
# Protobuf Python Version: 6.33.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    0,
    '',
    'tesla_api/protobuf/universal_message/v1/message_status.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tesla_api.protobuf.universal_message.v1 import message_fault_e_pb2 as tesla__api_dot_protobuf_dot_universal__message_dot_v1_dot_message__fault__e__pb2
from tesla_api.protobuf.universal_message.v1 import operation_status_e_pb2 as tesla__api_dot_protobuf_dot_universal__message_dot_v1_dot_operation__status__e__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n<tesla_api/protobuf/universal_message/v1/message_status.proto\x12 tesla.proto.universal_message.v1\x1a=tesla_api/protobuf/universal_message/v1/message_fault_e.proto\x1a@tesla_api/protobuf/universal_message/v1/operation_status_e.proto\"\xac\x01\n\rMessageStatus\x12L\n\x10operation_status\x18\x01 \x01(\x0e\x32\x32.tesla.proto.universal_message.v1.OperationStatusE\x12M\n\x14signed_message_fault\x18\x02 \x01(\x0e\x32/.tesla.proto.universal_message.v1.MessageFaultEB\x88\x01\n(com.tesla.generated.universal_message.v1B\rMessageStatusZMgithub.com/teslamotors/vehicle_command/pkg/protocol/protobuf/universalmessageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tesla_api.protobuf.universal_message.v1.message_status_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n(com.tesla.generated.universal_message.v1B\rMessageStatusZMgithub.com/teslamotors/vehicle_command/pkg/protocol/protobuf/universalmessage'
  _globals['_MESSAGESTATUS']._serialized_start=228
  _globals['_MESSAGESTATUS']._serialized_end=400
# @@protoc_insertion_point(module_scope)
