# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tesla_api/protobuf/universal_message/v1/operation_status_e.proto
# Protobuf Python Version: 6.33.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    0,
    '',
    'tesla_api/protobuf/universal_message/v1/operation_status_e.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n@tesla_api/protobuf/universal_message/v1/operation_status_e.proto\x12 tesla.proto.universal_message.v1*_\n\x10OperationStatusE\x12\x16\n\x12OPERATIONSTATUS_OK\x10\x00\x12\x18\n\x14OPERATIONSTATUS_WAIT\x10\x01\x12\x19\n\x15OPERATIONSTATUS_ERROR\x10\x02\x42\x8b\x01\n(com.tesla.generated.universal_message.v1B\x10OperationStatusEZMgithub.com/teslamotors/vehicle_command/pkg/protocol/protobuf/universalmessageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tesla_api.protobuf.universal_message.v1.operation_status_e_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n(com.tesla.generated.universal_message.v1B\020OperationStatusEZMgithub.com/teslamotors/vehicle_command/pkg/protocol/protobuf/universalmessage'
  _globals['_OPERATIONSTATUSE']._serialized_start=102
  _globals['_OPERATIONSTATUSE']._serialized_end=197
# @@protoc_insertion_point(module_scope)
