# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tesla_api/protobuf/universal_message/v1/routable_message.proto
# Protobuf Python Version: 6.33.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    0,
    '',
    'tesla_api/protobuf/universal_message/v1/routable_message.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tesla_api.protobuf.signatures import signature_data_pb2 as tesla__api_dot_protobuf_dot_signatures_dot_signature__data__pb2
from tesla_api.protobuf.universal_message.v1 import destination_pb2 as tesla__api_dot_protobuf_dot_universal__message_dot_v1_dot_destination__pb2
from tesla_api.protobuf.universal_message.v1 import flags_pb2 as tesla__api_dot_protobuf_dot_universal__message_dot_v1_dot_flags__pb2
from tesla_api.protobuf.universal_message.v1 import message_status_pb2 as tesla__api_dot_protobuf_dot_universal__message_dot_v1_dot_message__status__pb2
from tesla_api.protobuf.universal_message.v1 import session_info_request_pb2 as tesla__api_dot_protobuf_dot_universal__message_dot_v1_dot_session__info__request__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n>tesla_api/protobuf/universal_message/v1/routable_message.proto\x12 tesla.proto.universal_message.v1\x1a\x32tesla_api/protobuf/signatures/signature_data.proto\x1a\x39tesla_api/protobuf/universal_message/v1/destination.proto\x1a\x33tesla_api/protobuf/universal_message/v1/flags.proto\x1a<tesla_api/protobuf/universal_message/v1/message_status.proto\x1a\x42tesla_api/protobuf/universal_message/v1/session_info_request.proto\"\xc1\x04\n\x0fRoutableMessage\x12\x45\n\x0eto_destination\x18\x06 \x01(\x0b\x32-.tesla.proto.universal_message.v1.Destination\x12G\n\x10\x66rom_destination\x18\x07 \x01(\x0b\x32-.tesla.proto.universal_message.v1.Destination\x12#\n\x19protobuf_message_as_bytes\x18\n \x01(\x0cH\x00\x12T\n\x14session_info_request\x18\x0e \x01(\x0b\x32\x34.tesla.proto.universal_message.v1.SessionInfoRequestH\x00\x12\x16\n\x0csession_info\x18\x0f \x01(\x0cH\x00\x12\x33\n\x0esignature_data\x18\r \x01(\x0b\x32\x19.Signatures.SignatureDataH\x01\x12N\n\x15signed_message_status\x18\x0c \x01(\x0b\x32/.tesla.proto.universal_message.v1.MessageStatus\x12\x14\n\x0crequest_uuid\x18\x32 \x01(\x0c\x12\x0c\n\x04uuid\x18\x33 \x01(\x0c\x12\x36\n\x05\x66lags\x18\x34 \x01(\x0e\x32\'.tesla.proto.universal_message.v1.FlagsB\t\n\x07payloadB\r\n\x0bsub_sigDataJ\x04\x08\x01\x10\x06J\x04\x08\x0b\x10\x0cJ\x04\x08\x10\x10)B\x8a\x01\n(com.tesla.generated.universal_message.v1B\x0fRoutableMessageZMgithub.com/teslamotors/vehicle_command/pkg/protocol/protobuf/universalmessageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tesla_api.protobuf.universal_message.v1.routable_message_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n(com.tesla.generated.universal_message.v1B\017RoutableMessageZMgithub.com/teslamotors/vehicle_command/pkg/protocol/protobuf/universalmessage'
  _globals['_ROUTABLEMESSAGE']._serialized_start=395
  _globals['_ROUTABLEMESSAGE']._serialized_end=972
# @@protoc_insertion_point(module_scope)
